#!/usr/bin/env bash

set -e
set -o pipefail

mkdir -p "/etc/X11/xorg.conf.d"

cat << EOF > "/etc/X11/xorg.conf.d/20-intel.conf"
Section "Device"
  Identifier "Intel Graphics"
  Driver "intel"
  Option "TearFree" "true"
EndSection
EOF
