#!/usr/bin/env bash

set -e
set -o pipefail

# https://askubuntu.com/a/905019

cat /etc/NetworkManager/conf.d/wifi.scan-rand-mac-address.conf << EOF
[device]
wifi.scan-rand-mac-address=no
EOF

service network-manager restart

